### ISSUE TITLE
bbox-limiting geocodes

### ISSUE THREAD

**Issue by tmcw** [mapbox/carmen#105]
It's pretty common practice for geocodes to have a bbox preference, so that places within your current mapview are favored. We could maybe do this client-side if it's really just a 'sort' process, but I think something like 'bbox of chicago, look for main street', it won't be practical to find all main streets and then filter then client-side. If that makes any sense.

**Comment by ingalls** [comment]
We now have a `proximity=[lng,lat]` options which accomplishes this.

**Comment by ian29** [comment]
- (a) returning all geocodes within proximity of 1 point and
- (b) returning all geocodes strictly within a given bounding box

are different things. this ticket is about (b), no?

**Comment by ingalls** [comment]
> so that places within your current mapview are favored

When we were first looking at a proximity mode is was between a bbox based and point based approach. In the end we decided to go with a point based approach.

@tmcw correct me if I'm wrong but the intent behind this ticket was about having a proximity mode and not the specific method in which it was accomplished (bbox vs prox) and therefore our current `proximity=[lng,lat]` fulfills this.

**Comment by tmcw** [comment]
heyo https://www.mapbox.com/api-documentation/#request-format
