### ISSUE TITLE
Geocoder duplicate and missing results

### ISSUE THREAD

**Issue by notflip** [mapbox/carmen#119]
When using the geocoder, When i search for a city, it returns a street in that city, not the city itself. And some streets are shown multiple times.. ( see screenshot )

You can see an example if i query for 'drongen' a city, it returns an address
http://api.tiles.mapbox.com/v3/notflip.hojkfi0h/geocode/drongen.json

![mb](https://cloud.githubusercontent.com/assets/4146384/3019678/655c0962-df95-11e3-979b-671da45d4a53.jpg)

**Comment by ingalls** [comment]
Hey @notflip this should be fixed in the latest version of the mapbo API. If you have any more problems give us a shout: help@mapbox.com
