### ISSUE TITLE
Allow reverse only sources

### ISSUE THREAD

**Issue by ingalls** [mapbox/carmen#123]
Right now carmen must have an index and vector tiles to use a source. 

Forward geocoding requires both of these but reverse geocoding only requires the vector tiles. A reverse only source should be able to be used without generating an index that is not going to be used.

**Comment by camilleanne** [comment]
@ingalls is this still the case?

**Comment by ingalls** [comment]
Yes, at the moment this is still the case.

**Comment by ingalls** [comment]
I think the use case for this is pretty minimal with the release of the surface API. We can circle back in the future if a use case unveils itself.
