### ISSUE TITLE
Include type of place in results

### ISSUE THREAD

**Issue by hampelm** [mapbox/carmen#133]
It would be helpful to have an explicit geography type returned with each result. For example, the result for `san francisco, ca` would be of type `city`. `155 9th street` would be an `address`. This would help with verifying results, among other uses cases. 

Currently, the feature's id property has some clues (like `address.110498934605`), but isn't always correct. For example, `market street san francisco, ca` has an id of `address.110498934605`, but has the line segments for the road.

**Comment by ingalls** [comment]
Hey @hampelm you should be able to differentiate between a street level result and an address level type by looking for the presence of an `address` key. ie `"address": "1600"`

Let me know if you have any problems.
