### ISSUE TITLE
Date line causes problem with bounds

### ISSUE THREAD

**Issue by dhcole** [mapbox/carmen#19]
Look at an [example response for New Zealand](http://api.tiles.mapbox.com/v3/dhcole.map-711t5gj9/geocode/New%20Zealand.json), it looks like the bounds returned do not take into consideration the date line, where `bounds[0]` should be the minimum longitude is actually the maximum longitude.

```json
{
    "bounds": [
        -177.956962444279,
        -52.5773064168166,
        178.844049520022,
        -8.54335337282838
    ]
}
```

**Comment by dhcole** [comment]
👋

**Comment by yhahn** [comment]
@dhcole :moneybag: :wink:
