### ISSUE TITLE
Limit tile-cover per feature

### ISSUE THREAD

**Issue by yhahn** [mapbox/carmen#195]
https://github.com/mapbox/carmen/pull/190 problem identified here crops up when,

- A single feature has a huge tile-cover list (e.g. Russia) or
- A lot of features contribute to a huge tile-cover for a given phrase

I'm still mulling on what the latter means but the former we should limit so we know what we're up against. Not sure what the real solution will be (multi-zoomlevel tile covers?) but in any case generating indexes with huge tile-covers is probably not a good idea.

cc @karenzshea @ingalls

**Comment by ingalls** [comment]
Limiting tiles was implementing to handle canada & russia tile covers being too large.

**Comment by ingalls** [comment]
Limiting tiles was implementing to handle canada & russia tile covers being too large.
