### ISSUE TITLE
Token replacement as a series of regexes

### ISSUE THREAD

**Issue by yhahn** [mapbox/carmen#201]
Currently token replacement occurs after a query has been tokenized:

    "fourteenth street northwest" => tokenize,
    ["fourteenth", "street", "northwest"] => use index-specific mapping,
    ["14th", "st", "nw"] => use replaced version for querying

This means token mappings can only map `from:to` where `from` matches something post-tokenization:

    "fourteenth": "14th",

### Problem

This approach is fast + simple in implementation but can't handle normalization in languages like French where hyphenated combinations are a norm:

    Nord-Est=NE

It's also the kind of pre-processing we'll need to handle complex housenumbers like

    Lot 5

Or

    P-27

### First prototype

Transform the `geocoder_tokens` lookup hash at index load time with a function that does regex-based replacement.

    "fourteenth street northwest" => use index-specific replacer function,
    "14th st nw" => tokenize,
    ["14th", "st", "nw"] => use replaced version for querying

cc @karenzshea @ingalls @sbma44

**Comment by yhahn** [comment]
@karenzshea @sbma44 to start, we need a way to construct regexes that target a single token and can replace it intelligently.

    // naive replacement
    > ('15th street streetsville').replace(/street/ig,'st');
    '15th st stsville'

Instead, we'd want the desired result to be something like

    '15th st streetsville'

Where we replace `street` only if it is separated from other parts of the query by certain characters like spaces, dashes, etc. I'm not sure if this is possible to do with a single regex replace or if we'll need some more logic around it.

Getting started:

- playing around with regexes
- a good body of testcases with weird scenarios (dashes, apostraphes, etc.)
- adding a util function in a branch + having unit tests against it to confirm it works

**Comment by sbma44** [comment]
This example can be solved with matching groups for the word boundaries, reinserting them around the replacement text:

```
('15th street streetsville').replace(/([\s\-])street([\s\-])/ig,'$1st$2');
```

If we wind up with crazier situations we can dig into [replacement functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_function_as_a_parameter) 

I am guessing that @karenzshea has  better idea of how to assemble weird testcases (I have weird Japanese data but no token replacement to do against it). I'm happy to help write tests against them.

**Comment by karenzshea** [comment]
I've got a [branch up] (https://github.com/mapbox/carmen/tree/lets-get-weird) with a first pass at this script, more or less using that .replace() method @sbma44 with a little modification to handle dynamically creating regex objects.

I have some tests up as well, but they're mostly just telling me what I that the little function works. Afaik, other places that will need updating to move this effectively into carmen are
- termops: take out token replacement
- other scripts using termops

That's a weak list. I'm hoping that @yhahn & @ingalls you have a better overview idea of what this will affect. For now I'm going to look into refactoring termops

**Comment by karenzshea** [comment]
Implemented `token.js` where needed with @yhahn

capturing what to look into:
- speed
- what else is affected by change in indexer

**Comment by karenzshea** [comment]
With the implementation of `1.9.2-dev`, sample addresses that carmen doesn't like right now : 
- 181 Ch Des Ormeaux Ste-Catherine-DE-LA-J-Cartier
- 235 Rang DE LA Riviere Nord Saint-Roch-DE-L'Achigan

with the error
`libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: misuse: setRelev.relev > 5 bits
Abort trap: 6`

Could mean 
- relevance is being scored above 1
- ???

cc @yhahn

**Comment by yhahn** [comment]
thx, I'll debug this to confirm/deny the suspicion that this is a relev score going above 1 (which we previously assumed would never happen).

https://github.com/mapbox/carmen-cache/blob/master/src/binding.cpp#L837-L839
