### ISSUE TITLE
determine what happens if context includes both point & poly

### ISSUE THREAD

**Issue by sbma44** [mapbox/carmen#212]
capturing task for @ingalls from chat. if this provides insufficient clarity, pls consult your notes:

![image](https://cloud.githubusercontent.com/assets/31717/5984453/572fab0e-a8a4-11e4-899a-857fb6739ee8.png)

**Comment by yhahn** [comment]
o yes of course

**Comment by ingalls** [comment]
As per the new tests in  #213, when a combines polygon/point layer is used, the polygon is always returned.

**Comment by sbma44** [comment]
@ingalls hm ok. should I punch out GB from postcode-ephemeral-tomtom with `post.exclude-country.sh` then? not sure if that'll work since it was designed for quattro but I imagine it can be adapted
