### ISSUE TITLE
Failing test

### ISSUE THREAD

**Issue by springmeyer** [mapbox/carmen#215]
I'm noticed that carmen master is passing on travis. However when I install carmen as a dependency and run its tests I'm hitting this failure:

```
/home/travis/build/mapbox/mapnik-swoop/node_modules/carmen/index.js:41
        results.forEach(function(info, i) {
TypeError: Cannot call method 'forEach' of undefined
    at Geocoder.<anonymous> (/home/travis/build/mapbox/mapnik-swoop/node_modules/carmen/index.js:41:17)
    at notify (/home/travis/build/mapbox/mapnik-swoop/node_modules/carmen/node_modules/queue-async/queue.js:45:26)
    at /home/travis/build/mapbox/mapnik-swoop/node_modules/carmen/node_modules/queue-async/queue.js:35:11
    at /home/travis/build/mapbox/mapnik-swoop/node_modules/carmen/node_modules/mbtiles/lib/mbtiles.js:231:44
    at Statement.errBack (/home/travis/build/mapbox/mapnik-swoop/node_modules/carmen/node_modules/mbtiles/node_modules/sqlite3/lib/sqlite3.js:16:21)
```

@ingalls @yhahn - any ideas on where to start looking? I'm seeing this at https://travis-ci.org/mapbox/mapnik-swoop/jobs/49543819#L1270. This is https://github.com/mapbox/mapnik-swoop which installs a bunch of modules - from their master version - and ensures tests pass with an upcoming node-mapnik version. In this case it does not look like the node-mapnik version is causing the test failures but rather something that changed in carmen that I need to adapt to? Like something changed with some new permission or S3 credential maybe?

**Comment by springmeyer** [comment]
@yhahn @ingalls So the above error does not happen when Carmen tests are run normally, but does happen when Carmen is run by mapnik-swoop. What mapnik-swoop does is install carmen into `node_modules` and then uses Node.js child process to call out to `npm test`: https://github.com/mapbox/mapnik-swoop/blob/master/test.js#L81-L85. 

I presume something obvious is failing given that custom setup, but I'm blind to what it is. One clue is that Carmen is the only dependency that fails. So, what about the Carmen tests are unique?

**Comment by yhahn** [comment]
Cool, I'll dig around. OTOH sounds like it may just be a path or something that needs to be smarter.

**Comment by springmeyer** [comment]
Just ran to completion for me locally with no errors. I saw:

```
carmen --> 
Missing version for mapnik. Need to run npm install ?
waiting...
waiting...
waiting...
waiting...
doc._center did not fall within the provided geometry for 1 (main st). Calculating new point on surface.
doc._center:  undefined
doc._zxy:     [ '6/18/24' ]
waiting...
waiting...
    ✓ carmen tests  (78408ms)
```

I think the `Missing version for mapnik. Need to run npm install ?` is coming out of retire and is a good thing: it shows the top-level mapnik is being used and not one within carmen/node_modules.

Not sure if the stderr of `doc._center did not fall within the provided geometry for 1 (main st)` is a problem.

`✓ carmen tests  (78408ms)` seems to indicate full success. Still waiting on travis to run so I can see if travis is still failing.

**Comment by springmeyer** [comment]
waiting on this travis run (with carmen added back in: https://travis-ci.org/mapbox/mapnik-swoop/builds/51280531)

**Comment by springmeyer** [comment]
travis run now passed (https://travis-ci.org/mapbox/mapnik-swoop/builds/51280531). So I'm not sure what fixed this, but its not longer an issue.

**Comment by karenzshea** [comment]
fyi @springmeyer I ran into this same issue this morning on a my carmen branch before I discovered https://github.com/mapbox/carmen/pull/218 locally. After I merged that change and re-`npm install`ed a couple times it seemed to fix itself too :expressionless:

**Comment by springmeyer** [comment]
Thanks @karenzshea - sorry about the unanticipated breakage.

**Comment by springmeyer** [comment]
oh wait @karenzshea - I thought you commented and I was responding on https://github.com/mapbox/carmen/pull/218. So, you also hit the `TypeError: Cannot call method 'forEach' of undefined` error?

**Comment by karenzshea** [comment]
Yep, I can't recreate it now though and couldn't figure out what was causing it. Something wasn't getting returned from the selected indexes?
