### ISSUE TITLE
lib/index.js assumes metadata already present at destination index

### ISSUE THREAD

**Issue by sbma44** [mapbox/carmen#288]
at https://github.com/mapbox/carmen/blob/master/lib/index.js#L98 `source._geocoder.geocoder_tokens` will often be empty: rather than being the source index (as the name implies), that variable contains the destination index.

If the destination index has already had its metadata updated (for instance, by [tilelive-copy](https://github.com/mapbox/tilelive.js/blob/master/bin/tilelive-copy)) this isn't an issue: the metadata will have already been copied over. If it hasn't, token replacement won't happen.

**Comment by yhahn** [comment]
:+1: thx for tracking this down -- let's land a fix for this post `c4` to avoid conflict-city...

**Comment by ingalls** [comment]
@sbma44 did this get fixed? Good to close or further actions?

**Comment by sbma44** [comment]
@ingalls I have to be honest, I have absolutely no recollection of writing this ticket. Closing as stale.
