### ISSUE TITLE
Debug stats for detected collision

### ISSUE THREAD

**Issue by yhahn** [mapbox/carmen#321]
We eliminate features at verifymatch that might have snuck through to the end because of phrase hash collisions. We could count and surface the count of this for a given query into the debug stats. This would give us a way to verify that the `nintendo64` branch is getting us what we hope for -- lower hash collisions.

cc @ingalls

**Comment by yhahn** [comment]
https://github.com/mapbox/carmen/blob/master/lib/verifymatch.js#L99-L101

**Comment by ingalls** [comment]
Stale
