### ISSUE TITLE
sphericalmercator@1.0.4 causes test failures

### ISSUE THREAD

**Issue by camilleanne** [mapbox/carmen#339]
fix for minY and maxY flips (https://github.com/mapbox/node-sphericalmercator/pull/13) breaks tests for `context()`.

Making the `min` values here https://github.com/mapbox/carmen/blob/master/lib/context.js#L111-L112 reference `max` instead fixes the tests, but I'm not sure if it's a [bad test](https://github.com/mapbox/carmen/blob/master/test/geocode-unit.backy.test.js#L53-L70) or a bug in carmen yet. @yhahn any thoughts?

**Comment by ingalls** [comment]
We've removed `sm` and replaced it with `tile-cover`. These instances should now be fixed.
