### ISSUE TITLE
support queries for intersections

### ISSUE THREAD

**Issue by sbma44** [mapbox/carmen#349]
e.g. "5th & Main St"

**Comment by twbell** [comment]
This convention is employed only in a very select number of countries: US is P1, any others P2.  It is used widely enough in the US that it merits serious consideration (however naff we think it may be in an addresspoint world).

**Comment by bennlich** [comment]
Currently working with a dataset of US intersections. Wondering if there's a way around this, but thinking I'll have to use a different geocoding API.

**Comment by KaiBot3000** [comment]
Hi @bennlich, this is a feature that we'd love to have and have started work on, but it isn't a high priority at the moment. We'll happily accept a pull request implementing it!

**Comment by bennlich** [comment]
@KaiBot3000 kk, thanks for the reply!

Not sure if I have the time/ability to really dive into this, but assuming I did, where'd be a good place to start reading the code?

Is the strategy to identify "5th & Main St" as a special kind of query and take it down its own code path, looking for an intersection of two polylines?

**Comment by andrewharvey** [comment]
You might be able to implement it client side too, splitting the query into two queries "5th Street" then "Main Street", however for this you'd want the result to return a street with a LineString geometry, rather than a point in the centroid of the street.

**Comment by KaiBot3000** [comment]
Hey @bennlich that sounds like a great approach to try. Carmen doesn't return full geometries on purpose; at Mapbox we're often working with proprietary datasets that we don't want to return in responses.

**Comment by KaiBot3000** [comment]
@bennlich I've put in some work on this quest already; feel free to check it out over in the [`[crossnodes]`](https://github.com/mapbox/carmen/tree/crossnodes) and [`[cross-street]`](https://github.com/mapbox/carmen/tree/cross-street) branches. At the very least you'll be able to use the failing test cases. It's been a while since I've touched either of those branches, but let me know if you run into any issues or have questions.

**Comment by AddoSolutions** [comment]
I have an application that relies heavily on the geocoding of intersections (10k lookups/day).  Any recommendations on how to get around this?
