### ISSUE TITLE
Move from a hash table to a bit array for the "ldict" cache

### ISSUE THREAD

**Issue by apendleton** [mapbox/carmen#359]
Carmen-cache currently uses a hashtable to figure out which terms are in its full-sized cache, and checks terms in that cache to decide whether or not to do the IO to retrieve full records. That hashtable ends up being huge. We've already [shrunk the hashes to 32 bits](https://github.com/mapbox/carmen-cache/pull/41), but that hasn't been enough.

New strategy: rather than using a hash table, use hashes of terms as indices into an array of bits, with the bit being 1 if the hash is in the set or 0 otherwise.  32 bits is still too big, but we don't have to go all the way down to another power of 2 as we no longer have to be byte-aligned. 28 bits is a good candidate; each index would be 2 ^ 28 bits or 2 ^ 25 bytes, which is 32 megabytes. Totally manageable.

We'll then store each cache in a buffer, and gzip it for storage. All of this will move from C++ land to the node side.

**Comment by apendleton** [comment]
I tested possible bit depths, focusing on this function: https://github.com/mapbox/carmen/blob/master/lib/phrasematch.js#L52-L69

And totally how many total results it generated globally over the course of an entire test run. Cache collisions should lead to extra work as carmen does IO for terms that aren't actually in the full cache, so this number should increase over time.

The test was ~1500 forward geocode queries pulled from actual traffic, and run against a development server. The following is the global total for each run, along with the bit depth of the cache. Note: collisions probably become more frequent with increased cache sizes, so the production curve might look slightly different from this, but I think these results should still be pretty useful.

bit depth | total result count
------------|------------
32 | 68990
28 | 69132
24 | 72090
20 | 109894
16 | 279141
12 | 596707

The 12-bit number might not be trustworthy as the process was throwing various kinds of errors as it ran. 16 and 12 bit were both very slow to run, which is unsurprising due to their extra IO.

28 seems safe. 24 is probably also fine, and intermediate values would be too. Of course, each reduction in bit depth by one bit should double the collision rate and halve the cache size.

**Comment by yhahn** [comment]
@apendleton leapfrogged :frog: with https://github.com/mapbox/dawg-cache
