### ISSUE TITLE
yo-dawg backlog

### ISSUE THREAD

**Issue by yhahn** [mapbox/carmen#384]
- [x] dawg-cache: node-pre-gypify, static binaries for OSX + linux (https://github.com/mapbox/dawg-cache/pull/1)
- [x] carmen: get tests working on circle
- [ ] ~~make sure swappable dictcache interface is working properly (need to :eyes: on making sure geocoder_dictsize arg keeps working...)~~
- [x] :eyes: on dawg-cache deps
- [ ] IRL indexing + testing

cc @apendleton pls update/revise as you see things :point_up:

**Comment by apendleton** [comment]
In yo-dawg at present, to keep the constructor signatures of the dawg cache and the bitcache the same, geocoder_dictsize: X has become geocoder_dictcache_opts: {size: X} for bitcache (and could be, e.g., geocoder_dictcache_opts: {char_width: Y} for some future enhancement of dawg; both would take a buffer as a first argument and an object with backend-specific options as a second argument). I can roll that back if that seems like a bad idea, but the matching branch in mapbox-places conforms to that change.

**Comment by apendleton** [comment]
dawg-cache deps are down to nan and node-pre-gyp, so marking that one done

**Comment by yhahn** [comment]
@apendleton ^^ want to roll a new and/or first dawg-cache release with new binaries?

**Comment by apendleton** [comment]
@yhahn okay, that's done.

**Comment by yhahn** [comment]
Done!
