### ISSUE TITLE
Support degens of pre-contracted tokens

### ISSUE THREAD

**Issue by yhahn** [mapbox/carmen#414]
We currently generate autocomplete degens for text by subtracting one letter at a time from a term. 

For a document with text like `main street` 

```
main street
main stree
main stre
main str
main st
main s
main
mai
ma
m
```

Currently, when there are replacement tokens involved we do the _replacement first_ and then generate degens only _once_ after the replacement:

```
main street => main st

main st
main s
main
mai
ma
m
```

This means we lose autocompletion matching for quite a few permutations:

```
main stree
main stre
main str
```

:disappointed: 
### We're going to fix this!

The fix for this will require becoming familiar with a small portion of the carmen indexer starting with how we deal with doc text. We'll start with the tests and work backwards from there.

cc @aarthykc @arunasank

**Comment by miccolis** [comment]
Stale `123 main stree` works fine now-a-days
