### ISSUE TITLE
Incorrect interactions between unidecode and token replacement

### ISSUE THREAD

**Issue by apendleton** [mapbox/carmen#424]
I just dug into an issue where a query for the string "Rua Oratório" returned a correct result and "Rua Oratorio" did not, and several issues came up. In general, we handle squashing accented characters in inbound queries correctly, but failed this time. It turns out the token replacement operation is being performed on text pre-unidecode, but the regular expression for identifying words is "\W+" which maps to [^a-zA-Z_0-9] and thus excludes accented characters. Consequently, the terminal "rio" in the accented version matched a predefined Portuguese substitution "rio" => "r", which transformed "Oratório" into "Oratór" and then into "orator" (after lowercase and unidecode). This didn't happen in the unaccented version, which was left free of transformations. As the index-time string also had the accented character, the same behavior occurred at index time as at search time with the accented character, and that version matched, whereas the unaccented version didn't.

So, a few problems:
- The word-boundary regex in the token replacer fails to account for unicode characters, but unicode strings are being passed in
- The token replacement code generally doesn't assume unicode characters in other ways; the to- and from- replacer strings are unidecoded when the token replacer is built, for example. This means all replacement strings with accented characters currently don't work as intended, because the index-time strings still have their accents whereas the to/from strings have had their accents stripped
- Conversely, if end-user queries omit accents, they _do_ have replacements applied even though they weren't applied at index time

A lot of this probably stems from [moving the unidecode operation later in the process](https://github.com/mapbox/carmen/commit/7b0083f) to fix degen generation for Chinese characters, I think? So moving unidecode earlier in the process is probably not straightforward.

@ingalls and I talked it through and each have ideas, but would be curious to hear others' thoughts.

cc @yhahn @sbma44 @camilleanne

**Comment by apendleton** [comment]
Concretely as to a fix, three directions we could go:
* **Option 1:** Keep unidecode late as it is, and fix the token replacement's handling of unicode text. Specifically, first I think this would involve changing how word boundaries are represented in the token replacement regex, probably to be a positive set rather than a negative one, so rather than no letters or numbers, it should be all whitespace and punctuation. Second, for the from- and to- replacement strings, for all the ones that contain accented characters, add them twice, once with accents and once without, so they work the same way regardless of whether user queries have accents or not.  This is probably my current inclination.
* **Option 2:** move the unidecode step back to earlier in the process and implement the degen logic around Chinese characters some other way.  I don't really know how this would work.
* **Option 3:** do two passes of the unidecode step, a "lite" version that only strips accents but doesn't do one-char-to-multi-char expansions, which we would do at the beginning, and a full version, which would transform everything, which we would do at the end as it is now.  I think this is @ingalls ' preference.

**Comment by camilleanne** [comment]
I'm not sure yet how I'm thinking about this, but we do do some moving around only chinese characters here: https://github.com/mapbox/carmen/blob/9ba3663cb4ec0ec37e8ad410357ec0bbf09065b5/lib/util/termops.js#L125-L127

It's a bit slow and not that elegant, but maybe if that could get bundled up into another step it would make more sense

**Comment by apendleton** [comment]
@camilleanne good to know. I think for our purposes here "Chinese" should maybe be "multi-byte characters," or actually probably "characters whose unidecode expansion is more than one byte long," as we get ready to add more languages. But yeah, something like that would be doable if we can figure out where to put it.

**Comment by sbma44** [comment]
moving to a positive set of word boundary characters sounds like a good idea but I'm a little wary of the other half of option 1: inserting tokens with and without accents. This would amount to logic in option 3, right? I think these two options may be closer than it initially appears. If that's right, we might as well keep the total number of regexes down.

**Comment by apendleton** [comment]
@sbma44 yes, they're similar. It's just a question of whether the transformation logic is applied to the replacement strings or to input queries. The former is actually somewhat stricter... if you imagined the token replacement "São" => "S" being applied to the input string "Sáo" (different accent), the option 1 version would not apply the transformation because the two things in the token replacer would be "São" and "Sao," but not "Sào," whereas in option 3 the input string and the replacement string would both be transformed into "Sao," so replacement would be applied incorrectly. I kind of doubt this actually happens much, though.

Mostly I think option 3 would just be more work, because we'd have to write the thing that knows how to strip accents but not expand characters, which we don't have right now, whereas for option one we could just apply current-unidecode to the token replacement strings. And as far as regex counts: most replacement tokens don't contain accents, so I don't think this would actually increase the count much. We'd only need to duplicate for instances where it mattered.

**Comment by sbma44** [comment]
This makes sense -- I didn't appreciate that option 1 would allow us to employ unidecode as-is. And your argument on regex performance makes sense.

Curious to hear others' thoughts, but I'm leaning toward option 1 as well, largely because I'm not confident in our ability to cover all accent-stripping cases correctly.

**Comment by apendleton** [comment]
I think the modified unidecode would basically use the subset of the substitution tables where the character count going in and the character count going out are both 1... not 100% confident that would be right, but it's probably no worse than unidecode generally, I think?

**Comment by mtmail** [comment]
Over time the word boundary splitting will need to become more complex. Think about `L'Auberge`, `St. John's Close`, `O'Reilly` or `Chicago O'Hare Airport` (plus data containing various mistyping of quote signs).
For splitting by dashes and forward slashes (or even brackets) there's no one good answer. Sometimes keeping the words together produces better search results, sometimes splitting. I tend to try both combinations when words are split by dashes and treat forword slashes like commas, though Carmen doesn't use them as word boundary hint I think.

**Comment by apendleton** [comment]
@mtmail this isn't for proper tokenization, just for identifying places for token replacement. These tend to be very simple cases like reducing "Road" to "Rd," with the substitution set known in advance; in practice I don't think we've run into situations like the ones you describe. The actual tokenization operation can be (and is) more complex/expensive.

**Comment by apendleton** [comment]
Though now that I'm thinking about it @yhahn @arunasank @aarthykc we should consider how this interacts with https://github.com/mapbox/carmen/issues/414

**Comment by apendleton** [comment]
Per chat, going with the first option.

**Comment by apendleton** [comment]
Actually, good news! The logic to add both the unidecoded and non-undecoded versions of tokens to the replacer is already in carmen; we just didn't read the logic correctly on the first pass. It's [here](https://github.com/mapbox/carmen/blob/master/lib/util/token.js#L12-L19). So the problem should actually just be with the word boundaries.
