### ISSUE TITLE
tighten behavior around cross-charset unidecoded false positives

### ISSUE THREAD

**Issue by sbma44** [mapbox/carmen#433]
Everything in Carmen indexes is transliterated by the `unidecode` module into a string of ASCII characters. As additional language data is loaded, more collisions are becoming apparent. One recent example:
- `Alberta` is a province in Canada
- it's called `アルバータ州` in Japanese
- unidecode transforms this to `arubataZhou`
- ... which matches an autocomplete (default) query for "Aruba"

Unidecode performs several functions for us:
- it's a lossy hash to collapse unicode into more compact ASCII
- it cleans up accents on latin character sets
- it provides _some_ transliteration capability, allowing queries across character sets

Preserving this third behavior looks increasingly tenuous--there are probably better long-term approaches to that problem. But that's a larger conversation.

In the short term, we need to reduce our incidence of false positives, particularly for CJK terms. @apendleton suggested an elegant approach: detect the string character set, then prefix it with a letter (say, `C` for `CJK`, `M` for mixed/everything else).

We could separate out other character sets like Cyrillic but a) haven't yet observed problematic behavior with it b) think it might work better for transliterations than CJK. 

This will require a global reindex. Also, character set detection may not be trivial.

cc @yhahn @apendleton @ingalls @camilleanne

**Comment by apendleton** [comment]
Copying what I added in chat:

> Actually, thinking more, I think the super-simple solution that combines several already-proposed ideas: we pick a single ascii character that will never occur in unidecode output, and if the source string contains any characters in complex alphabets, we prefix with that before storing in or looking up from the dawg, so then we have two trees, basically.
> 
> I think this could actually be pretty fast to hack together, and English/otherwise-Latin text stays the same in the dawg as it is now.

The last property would help shield us from any unforeseen behavior changes this might introduce (though I don't think there would be any).

**Comment by apendleton** [comment]
Also, for alphabet detection, haven't found anything for node, but this Python library does what we want: https://github.com/EliFinkelshteyn/alphabet-detector so might be worth figuring out how it works.

**Comment by tmcw** [comment]
Alphabet detection... someone shine the @ericfischer bat signal

**Comment by ericfischer** [comment]
@tmcw The one I've used before is https://github.com/mikemccand/chromium-compact-language-detector. (The old version that I used was https://github.com/ericfischer/chromium-compact-language-detector; I'm not sure what has changed since then.)

Or are you just wanting to know script, not language? Just the Unicode block of the alphabetic characters ought to be enough for that.

**Comment by apendleton** [comment]
@ericfischer yes, just script. There ought to be some simple library for doing that, right?

**Comment by apendleton** [comment]
Ooh, maybe we could go with this hackery: http://kourge.net/projects/regexp-unicode-block

**Comment by ericfischer** [comment]
If all we need is the script, checking it with regular expressions is as good an idea as any I have.

**Comment by mtmail** [comment]
The Python library just looks at the unicode character name, the https://en.wikipedia.org/wiki/Unicode_block detecting by regexp should be good enough to start with.

**Comment by sbma44** [comment]
The regex approach looks good to me. I'll take a pass at adding this to the tokenization code.

**Comment by sbma44** [comment]
As a first pass I'm checking for the following blocks:
- Hangul Jamo
- CJK Radicals Supplement
- CJK Symbols and Punctuation
- Hiragana
- Katakana
- Bopomofo
- Hangul Compatibility Jamo
- CJK Strokes
- Katakana Phonetic Extensions
- Enclosed CJK Letters and Months
- CJK Compatibility
- CJK Unified Ideographs Extension A
- CJK Unified Ideographs
- CJK Compatibility Ideographs
- CJK Compatibility Forms

I suspect this list is longer than it needs to be, which doesn't bother me much. It could also easily be leaving out blocks I should be checking for, which is more concerning.

**Comment by sbma44** [comment]
this was merged
