### ISSUE TITLE
wipe() function not implemented

### ISSUE THREAD

**Issue by mtmail** [mapbox/carmen#439]
The README file documents`wipe(source, callback)` but such a function doesn't exist in the code. I did a rather simple grep in the repository and node modules. I've no immediate use for such a function, just wanted to let you know to maybe update the documentation.

**Comment by sesam** [comment]
I'm just lurking, but if you feel up to it, maybe a pull req.? Your excellent writeup just now looks as if you could be a savior for any project's documentation needs.

**Comment by mtmail** [comment]
Filed a pull request for a bug just yesterday (https://github.com/mapbox/carmen/pull/437). :)

Joking aside, it's not clear if the function is even needed. Sure, somebody might find it useful, but Mapbox who run Carmen in production didn't need so far and neither did I during my testing.

**Comment by KaiBot3000** [comment]
Thanks for pointing this out! I PR'd it here: https://github.com/mapbox/carmen/pull/653 and we'll take it along in our next release.
