### ISSUE TITLE
carmen calls countries stacks, causing a mismatch between input and output

### ISSUE THREAD

**Issue by tmcw** [mapbox/carmen#454]
Input URL:

```
https://api.mapbox.com/geocoding/v5/mapbox.places/vancouver.json?country=US&access_token=...
```

Output error:

``` json
{"message":"Stack \"US\" is not a known stack. Must be one of: cn, au, nz, sg, br, ca, at, de, dk, es, fr, nl, gb, ie, us, ao, bw, dz, eg, ke, ma, za, ae, bh, bn, id, in, jo, kw, my, ph, th, tw, vn, ad, al, ba, be, bg, by, ch, cy, cz, ee, fi, gr, hr, hu, is, it, lb, lt, lu, lv, md, me, mk, mt, no, pl, pt, ro, rs, ru, se, si, sk, sm, tr, ua, jp, ar, cl, co, cu, gf, gp, mx, pe, uy, ve"}
```

What is a stack? Carmen knows, but this isn't mentioned anywhere in our documentation and this would be a very confusing error message for a user who is just tinkering around with the API for the first time. Instead, we should say

``` json
{"message":"Invalid country code provided. Currently supported country codes: cn, au, nz, sg, br, ca, at, de, dk, es, fr, nl, gb, ie, us, ao, bw, dz, eg, ke, ma, za, ae, bh, bn, id, in, jo, kw, my, ph, th, tw, vn, ad, al, ba, be, bg, by, ch, cy, cz, ee, fi, gr, hr, hu, is, it, lb, lt, lu, lv, md, me, mk, mt, no, pl, pt, ro, rs, ru, se, si, sk, sm, tr, ua, jp, ar, cl, co, cu, gf, gp, mx, pe, uy, ve"}
```

The revised error also intentionally removes the string interpolation to avoid the reflection that could be used in an XSS attack with a bad client.

**Comment by ingalls** [comment]
As @apendleton points out in the code comment, carmen has no understanding of a country/state/etc so this needs to be caught at a different level of the stack. This specific error can then be caught and the message changed.

**Comment by tmcw** [comment]
Is there a potential of this getting fixed on the carmen side?

**Comment by apendleton** [comment]
@tmcw yep. This has been on my list but I haven't prioritized it, but I think I'm going to have some downtime in the next couple of days waiting for another feature to land, so I'll take care of it. Thanks for the nudge.

**Comment by tmcw** [comment]
Can we push https://github.com/mapbox/carmen/pull/455 as an interim fix?

**Comment by apendleton** [comment]
@tmcw sure. I just restored your old branch and pushed a change that I think addresses the concern you raised leading you to close it before. Did you have a corresponding api-geocoder branch that caught error and displayed something country-specific or does that still need to be done?

**Comment by ingalls** [comment]
Ok to close?

**Comment by apendleton** [comment]
@ingalls we never decided how to fix it, and it's still an issue... so, probably not, no
