### ISSUE TITLE
id search

### ISSUE THREAD

**Issue by ingalls** [mapbox/carmen#481]
searching by id

ie: `address.1234` should return with a relev of 1.

cc/ @mapbox/geocoding-gang

**Comment by mattficke** [comment]
@ingalls is there a particular reason you want this changed, out of curiosity?

Right now the relevance is set to the `carmen:score`: https://github.com/mapbox/carmen/blob/master/lib/geocode.js#L131

Which is useful to have, but potentially could be moved to a different field if 0 relevance is causing problems.

**Comment by mattficke** [comment]
Per chat, let's change this to what @ingalls suggests.

**Comment by apendleton** [comment]
It looks like relevance being set to score started with this commit: https://github.com/mapbox/carmen/commit/9c33335111504fd188bdd4635e3c96ac3a1c3422

But it's not clear to me why. Long time ago, obviously, so I doubt @ingalls remembers either.
