### ISSUE TITLE
Inconsistent CJK char code range

### ISSUE THREAD

**Issue by mattficke** [mapbox/carmen#509]
We use two different ranges to test for CJK characters in `termops`.

The full range is used to prepend an `x` or `z` to feature text, to separate language families:

```
[\u1100-\u11FF\u2E80-\u2EFF\u3000-\u303F\u3040-\u309F\u30A0-\u30FF\u3100-\u312F\u3130-\u318F\u31C0-\u31EF\u31F0-\u31FF\u3200-\u32FF\u3300-\u33FF\u3400-\u4DBF\u4E00-\u9FFF\uF900-\uFAFF\uFE30-\uFE4F]
```

However, when testing for CJK characters to determine how to split a query, we use the smaller CJK Unified Ideograph range, containing only the most common characters: `u4E00-u9FFF`

This leads to inconsistent results for CJK queries. The full range should be used for both purposes.

**Comment by sbma44** [comment]
Good catch! As the author of the scarequore-`full`-unscarequote range I should probably point out that it is based on eyeballing unicode docs, not a rigorous understanding of how the pieces fit together. I've had smarter people than me tell me that making a completely correct version of this is not possible.

**Comment by miccolis** [comment]
I don't think this ticket has been relevant in a while, the x/z prefixes were removed back in https://github.com/mapbox/carmen/pull/602
