### ISSUE TITLE
stack sort order is not completely deterministic

### ISSUE THREAD

**Issue by ansis** [mapbox/carmen#519]
The stacks of subqueries are sorted before they are slice to a max of 30 stacks. This is the sort function: https://github.com/mapbox/carmen/blob/021e4df61d3f2897cb0b9a2296892e77f02157e7/lib/spatialmatch.js#L228-L233

It is possible for `a` and `b` to be different but for all four of the comparisons to return `0`. In this case they are sorted in an undefined order.

I hit this when a phrasematch change caused the input array to be in a different order, which caused the sorted stack array to be in a different order, which caused a stack to get excluded by the slice, which caused a test failure.
- [ ] fix this sort
- [ ] check all other sorts for undefined behavior

**Comment by miccolis** [comment]
stale, closing.

PS Hi @ansis!
