### ISSUE TITLE
decide on token transitivity

### ISSUE THREAD

**Issue by ansis** [mapbox/carmen#522]
If you have the replacers `a => b` and `b => c` should `c` be considered a match for `a`?

Current master behavior: sometimes, depending on the order of the tokens.

I think the answer is no because you lose information and get unwanted matches. For example, if you have `saint => st` and `st => s` and `south => s` then all of a sudden you have `saint` matching `south.

On the other hand if you have multiple strings that should be treated the same (`saint`, `st`, `sankt`) then you need a replacer for each pair.

We also need to figure out the transitivity between global and source tokens. If you have the global replacer `a => b` and source replacer `b => c` should `c` be considered a match for `a`? I think the answer should also be no here but this is a bit trickier to implement.

**Comment by sbma44** [comment]
Hmm I _think_ the answer to the first is `yes` -- or at least that's what I wrote the system to do. This is enforced via the mapbox-places/scripts/token-combine.js script (which is en route to being moved to carmen-indexer). It attempts to organize tokens such that they are all transformed into the shortest token within the group. I can imagine some payoff to being stricter here but I also don't recall any instances of bugs where over-normalization of tokens led to the wrong result coming back. In practice I think these are low-value parts of the query.

I don't have any immediate insight into the second question but can think about it more if others don't chime in.

**Comment by ansis** [comment]
I implemented transitivity. I'm starting to have doubts about runtime tokenization.

This one is fun: `St. George Street 43 mountain station Mühleggbahn St Gallen`.
It's problematic because it's long and because many of the tokens have a high number of variations.

With the current tokens for `eur-place-both` there are 150000 variations of token replacements, before permutations. I think that would be 76,800,800 permuations before deduping. In the current implementation there are some duplicate replacements (because of differing capitalization), and a problematic `"S.": "S"` replacement that gets treated as a regex and joins the the street/saint replacements with the south/station replacements.

After fixing these I'm left with **12288 variations** (before generating the permutations!). The number of variations grows exponentially with the number of replacements. Here are the variations for individual tokens:

token | num variations | variations
---|---|---
st | 8 | st, saint, sankt, street, sint, stig, stora, stigen
george | 1 | george
street | 8 | street, saint, sankt, st, sint, stig, stora, stigen
43 | 1 | 43
mountain | 2 | mountain, mtn
station | 12 | station, sa, san, sta, stn, sud, santa, santo, south, södra, sodra, s
mühleggbahn | 1 | mühleggbahn
st | 8 | st, saint, sankt, street, sint, stig, stora, stigen
gallen | 1 | gallen

With the exception of `södra, sodra`, I don't think we can improve these token variations. They all look right to me.

Ways to fix this:
- keep doing what we've been doing for a long time: reduce all tokens in a group to a single abbreviation
- add a limit to the number of variations and just arbitrarily pick some (seems like this would be bad for quality and predictability)

cc @yhahn

**Comment by miccolis** [comment]
This is an old ticket but I've been wanting to capture the current state of play here and close it out. There are a few lines of inquiry here so I'll try to address each.

### Are token replacements transitive?
The intention is within carmen that they are not, however you can certainly provide carmen with a combination of global, complex and simple replacement that would create a situation where they are. To break this further down:

- Global replacements happen before anything else and essentially anything is allowed. So yea any change here would be subject to further replacement by both other global tokens and per-source tokens.
- Complex replacements, ones that change the number of words in a query or alter partial words, will have their results subject to further replacement. It's up to the implementer to decide if this is desired.
- Simple replacements, which swap one full word for another, are not transitive. We only attempt one transition.

### Should global replacements be subject to per-source replacements?
I agree with the OP that they shouldn't be, but that's pretty impossible as a direct task. What we are aiming for is a dramatic reduction in the need for global tokens. Once #826 lands we I expect we'll have a single global replacement remaining. That replacer help to emulate a address format we don't really support presently. Once we add proper support for that format (...and hopefully a structure that allows us to specifically target more than US style addresses) we'll have the option of dropping support for global replacers.

### Run time replacements
Agree that it's not really relevant to the original question at hand but... just to capture the present state of things 2.5 year later; at query time we don't generate variations. We "reduce all tokens in a group to a single abbreviation" at that seems fine for now.
