### ISSUE TITLE
Multilingual grid proposal

### ISSUE THREAD

**Issue by apendleton** [mapbox/carmen#547]
Currently, the grid cache is not language-aware. Doing multilingual autocomplete will likely require us to change that. Here's a proposal to do that. Aims:
* get rid of the current restriction that autocomplete only applies to default text (and remove the dot-suffix)
* make grid operations, coalesce, etc., language-aware, and specifically:
    * prefer matches in the user's requested language
    * still allow matches in a language other than the requested one, but with a relevance penalty
* be minimally invasive (most changes required here will be in `carmen-cache`)

The current grid cache structure works conceptually like:
```YAML
phrase1: [grid1, grid2, grid3, grid4]
phrase2: [grid5, grid6, grid7, grid8]
```

The proposed new format marks grids for a given phrase with a language bitmask:
```YAML
phrase1:
    lang_mask1: [grid1, grid2, grid3]
    lang_mask2: [grid4]
phrase2:
    lang_mask3: [grid5]
    lang_mask4: [grid6, grid7]
    lang_mask5: [grid4]
```

The language bitmask would represent, per index, the list of all known languages at index time. For example (assuming a 64-bit int for the mask, but can/should be bigger):
```
0000000000000000000000000000000000000000000000000000000000000000
|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||↳ default
||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||└→ ar
|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||└-→ az
||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||└--→ bg
|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||└---→ bn
||||||||||||||||||||||||||||||||||||||||||||||||||||||||||└----→ bs
|||||||||||||||||||||||||||||||||||||||||||||||||||||||||└-----→ ca
||||||||||||||||||||||||||||||||||||||||||||||||||||||||└------→ cs
|||||||||||||||||||||||||||||||||||||||||||||||||||||||└-------→ da
||||||||||||||||||||||||||||||||||||||||||||||||||||||└--------→ de
|||||||||||||||||||||||||||||||||||||||||||||||||||||└---------→ el
||||||||||||||||||||||||||||||||||||||||||||||||||||└----------→ en
|||||||||||||||||||||||||||||||||||||||||||||||||||└-----------→ es
||||||||||||||||||||||||||||||||||||||||||||||||||└------------→ et
|||||||||||||||||||||||||||||||||||||||||||||||||└-------------→ fa
||||||||||||||||||||||||||||||||||||||||||||||||└--------------→ fi
|||||||||||||||||||||||||||||||||||||||||||||||└---------------→ fr
||||||||||||||||||||||||||||||||||||||||||||||└----------------→ gu
|||||||||||||||||||||||||||||||||||||||||||||└-----------------→ he
||||||||||||||||||||||||||||||||||||||||||||└------------------→ hi
|||||||||||||||||||||||||||||||||||||||||||└-------------------→ hr
||||||||||||||||||||||||||||||||||||||||||└--------------------→ hu
|||||||||||||||||||||||||||||||||||||||||└---------------------→ id
||||||||||||||||||||||||||||||||||||||||└----------------------→ is
|||||||||||||||||||||||||||||||||||||||└-----------------------→ it
||||||||||||||||||||||||||||||||||||||└------------------------→ ja
|||||||||||||||||||||||||||||||||||||└-------------------------→ ka
||||||||||||||||||||||||||||||||||||└--------------------------→ kk
|||||||||||||||||||||||||||||||||||└---------------------------→ kn
||||||||||||||||||||||||||||||||||└----------------------------→ ko
|||||||||||||||||||||||||||||||||└-----------------------------→ lt
||||||||||||||||||||||||||||||||└------------------------------→ lv
|||||||||||||||||||||||||||||||└-------------------------------→ mk
||||||||||||||||||||||||||||||└--------------------------------→ mn
|||||||||||||||||||||||||||||└---------------------------------→ ms
||||||||||||||||||||||||||||└----------------------------------→ nb
|||||||||||||||||||||||||||└-----------------------------------→ nl
||||||||||||||||||||||||||└------------------------------------→ no
|||||||||||||||||||||||||└-------------------------------------→ pl
||||||||||||||||||||||||└--------------------------------------→ pt
|||||||||||||||||||||||└---------------------------------------→ ro
||||||||||||||||||||||└----------------------------------------→ ru
|||||||||||||||||||||└-----------------------------------------→ si
||||||||||||||||||||└------------------------------------------→ sk
|||||||||||||||||||└-------------------------------------------→ sl
||||||||||||||||||└--------------------------------------------→ sq
|||||||||||||||||└---------------------------------------------→ sr
||||||||||||||||└----------------------------------------------→ sr-Cyrl
|||||||||||||||└-----------------------------------------------→ sr-Latn
||||||||||||||└------------------------------------------------→ sv
|||||||||||||└-------------------------------------------------→ ta
||||||||||||└--------------------------------------------------→ te
|||||||||||└---------------------------------------------------→ tg
||||||||||└----------------------------------------------------→ th
|||||||||└-----------------------------------------------------→ tl
||||||||└------------------------------------------------------→ tr
|||||||└-------------------------------------------------------→ uk
||||||└--------------------------------------------------------→ ur
|||||└---------------------------------------------------------→ uz
||||└----------------------------------------------------------→ vi
|||└-----------------------------------------------------------→ zh
||└------------------------------------------------------------→ zh-Hans
|└-------------------------------------------------------------→ zh-Hant
└--------------------------------------------------------------→ zh-Latn
```

So we'd reserve one bit for default, and use bit for each known language.

Indexing would change as follows:
* for each feature, we would use the fallback mechanism from https://github.com/mapbox/carmen/pull/436 to pick a best-effort text choice for each language, so all features would have text for all languages in our language list. The extra language text does not get stored in the feature JSON, but is only used internally for populating the grid cache
* each grid store operation would add a given grid to the cache for a given phrase, tagged with a list of all languages for which that phrase corresponds to that grid (this means that the realization step above ^ does not cause duplication within the grid cache; we store the same number of grids as before, for the same number of phrases, but just flip on additional bits in the language mask on some of those phrases to fill in languages that don't already have translations present)

MVP of query time behavior searches all languages, with a fixed penalty for matches other than the one for the requested language (either natively or from index-time fallback, which are equivalent). It probably looks something like:
* per index, collapse the user's requested language into one of the languages in our language list for that index using our fallback code (so `en-US` becomes `en` right off the bat because we don't have `en-US`)
* enumerate phrases, and do the DAWG cache lookup as it's currently done; this step is not language-aware, so as now, the DAWG lookup tells us only "we have this phrase, period," not "we have this phrase in the requested language"
* specify what language we're looking for (or rather, which is closest from our list, per the first step) when we do retrievals from the grid cache
* that gets turned into a bitmask with one bit flipped, for the target language
* when we find our phrase in the grid cache, we have a bunch of language masks and a grid list for each. We iterate over these and flatten them out into a single list of grids, but with a relevance penalty applied to each grid if `target_mask & grid_language_mask == 0`.
* proceed to coalesce as per usual, with relevance penalties for mediocre matches applied. This should mean we consider the exact same list of grids as we do now, from the exact same grid shards (or actually, the same ones we did before the dot-suffix fix was applied), but some are now demoted

The fancier version of the query-time behavior applies a variable penalty depending on the language, so:
* at query time, rather than collapsing to a single language, we calculate a proximity from the requested language to each language in our known language list, and pass this whole matrix in on grid operations.
* at grid operation time, when we flatten the grid list as above, rather than a simple boolean operation to decide whether or not to penalize, we demote each grid entry according to the highest-scoring language in the given bitmask. This way, if a user says their language is `zh-HK` but they submit a query that contains the `zh-TW` text for a given feature, we barely penalize it since we expect these languages to be very similar, but we heavily penalize matches in, say, Norwegian, since these are likely not to be what the user meant.

This strategy is more computationally expensive though, also seems like a pain in the ass to implement, and requires us to come up with this proximity metric, which seems hard. Probably isn't necessary in the near term.

## Random other thoughts
For both: if the user doesn't specify a language we default to that first/least-significant bit in the mask. That will be the `_text` field for now, but needn't be forever if we come up with a better way of selecting default text (which we should, but that's a matter for another ticket). Also: for indexes that don't have translations at all (e.g., address indexes), we use the same grid cache format, but for each phrase we'll have only a single language mask, with all bits flipped to 1. We can potentially specifically detect this case and shortcircuit some bit arithmetic in carmen-cache if necessary.

Also-also: this is a change specifically to the grid-list part of the protobuf format. It's an orthogonal change to degenless in that sense, as that aspect doesn't change; it could be applied to any of the so-far-proposed degenless strategies, and could even be applied with degens present, but it will grow grid shards somewhat, so that seems like a bad idea.

Note on the language list: the list of languages we use should be the list of all languages we intend to support in our universe of indexes, not just the languages that happen to be present in the particular features going into a given index. Even if an index has no `zh-TW` text for any feature, if we know we want to support search for `zh-TW` we should have `zh-TW` bits in the grid cache so that we can copy `zh-Hant` text over as appropriate and match those features without penalty, so we can still return good `zh-TW` results. Ideally all indexes would have the same list, but I think it makes sense to store it per index so that adding languages does not require an immediate global reindex.

## Open questions
1. What do the carmen-side APIs for dealing with these look like? There are several possibilities, which I can flesh out in comments, but it largely boils down to how much of this we want to hide within carmen-cache from carmen.
2. Are there additional ramifications for how we match users' expectations in cases where we don't have the same languages available for all features in a given response? (I don't think so, but it's admittedly hard to reason about)
3. This definitely lets us get rid of the `.` suffix. Does it also let us get rid of the `x` prefix?
4. Is this a good opportunity to consider situation-specific relevance penalties more generally? e.g., https://github.com/mapbox/carmen/issues/521

cc @yhahn

**Comment by ansis** [comment]
I'm wondering if the language fallback logic could be moved from index-time to run-time.

- Instead of having a bitmask it would just store an int representing the language of the text.
- At query-time it would convert the user's language into a list of possible matches, in order of preference, for example `["pt-BR", "pt"]`.
- After the grid lookup, assigning the relevance penalties would be a bit more complex that with the bitmasks but it doesn't seem to bad. If all the grid entries are flattened you could do it in two passes by keeping track of the best language code for every feature id in the first pass, and assigning the penalty in the second.

The main advantage of this approach would be to let us change the fallback logic without having to re-index everything, but there might also be some minor space savings and handling more than 64 languages would be simpler. It also seems a bit more direct.

What are the advantages of the bitmask approach?

**Comment by ansis** [comment]
The thing that I was missing: with my suggestion you wouldn't have enough information at lookup time to know if a language is the best language for a feature since you don't know what other languages the feature has.

A couple more questions to help me understand:
- Instead of storing a bitmask of the languages for which this phrase is the best match could we store both a bitmask (or list) of the languages the feature has and the language for this phrase? This would move fallback logic from index-time to run-time?
- Why is important to penalize at the grid level instead of after features are loaded? Just to make the results before the `.slice(limit)`s better?

**Comment by ansis** [comment]
- How often would the fallback logic be tweaked? Would being able to change it without re-indexing be useful?

**Comment by apendleton** [comment]
@ansis yeah, the main motivation for the bitmask is if London's label is "London" in 20 languages I don't want to store twenty grid entries, I just want to store one, and tag it as being good for twenty languages. The bitmask means storing exactly the same number of grids as now, plus an overhead of one extra (maybe 128-bit?) int per unique combination of languages per phrase. The single-language int tag means an extra int per language per phrase, plus an extra grid per language per feature every time labels are shared between languages, which could grow grid shards by a lot.

But bitmask vs. other representation is probably a separate discussion from fallback at index time vs. fallback at runtime, I guess? That is to say, we could use bitmasks, but only encode actually-present languages instead of present languages and guesses. I need to think more about the advantage of that, though...

One goal here (which I should have made more explicit) was to make it so that even if we didn't store the index-time-generated fallback text in the feature JSON (which I'd prefer not to do for index size reasons), we'd use the same algorithm to calculate fallback behavior at index time as we would in selecting display text from the feature JSON in the query response, so that we'd minimize the instances where what the user typed didn't match what they saw in the response. This proposal doesn't get us all the way there, but it's a start, so I'd be hesitant about defining fallback behavior in multiple places (once in carmen for selecting display text vs. a different one with a different algorithm in carmen-cache for query matching) and introducing opportunities for inconsistency.

Another goal, definitely, is adding as little runtime overhead as possible. For some instances we're doing operations like "pull all the grids for things that start with `a`," and in some indexes that might be hundreds of thousands of grid entries. I can stomach adding an extra bitwise AND per language and a multiply for each underlying grid, but would rather avoid having, say, calculating the overlap of two lists of languages for every single grid, or doing hashtable lookups, or (especially) hitting a JS callback to decide match quality, all of which are likely to be horribly slow. I think the alternative to the simple AND/multiply would be to have a lookup table with precomputed penalty multipliers, which I discussed as the fancy option, above (and again, we could just do it once per phrase per language, not once per individual grid). That's probably where we should go eventually, but seemed like too big a lift to do now. Open to being persuaded there, though.

More specific answers:
> Instead of storing a bitmask of the languages for which this phrase is the best match could we store both a bitmask (or list) of the languages the feature has and the language for this phrase? This would move fallback logic from index-time to run-time?

For each feature in the grid cache we only have 53 bits to work with, and we're already using all of them. I think we can get this up to 64 if need be, but we won't ever be able to encode all the languages a given individual feature has in the grid cache. The phrase doesn't map to a single feature, it maps to all the features that have that phrase in that index, so the proposal here would be to add another level of nesting, so instead of `{phrase: [feature, feature, feature, feature]}` it's `{phrase: {langs: [feature, feature, feature, feature]}`. But each grid/feature/whatever-you-want-to-call-it is still 53 (or maybe 64) bits, and shouldn't get bigger if we can avoid it. Grid shards are already too big, and iterating over them is already too slow.

> Why is important to penalize at the grid level instead of after features are loaded? Just to make the results before the .slice(limit)s better?

Yeah, that's the idea. I think ideally we get the relevance right on the way into coalesce so that the right things make it over the cutoff and we can skip ever fetching tiles or feature JSON for poor matches. I think we also might not include all the translations in the tiles, but I might be misremembering there. I'm probably also a little biased because in some of the strings-attached work, some of the functionality this replaces (like query-time handling of the dot prefixes) already happens in carmen-cache...

This could all be premature optimization though, I'll admit.

> How often would the fallback logic be tweaked? Would being able to change it without re-indexing be useful?

No idea. The very first iteration of fallback behavior just went out last week. We already have at least one change planned to it, but I think after some immediate-term churn it will probably stabilize.

**Comment by ansis** [comment]
Thanks for the extra explanation!

**Comment by apendleton** [comment]
Okay actually this was a dumb plan. It interacts poorly with recent rocksdb work, and in particular, with the pre-truncated prefix caches, and also interacts poorly with grid merge, and some of the motivations predated the elimination of shards and resulted in some decisions that are no longer necessary.

New plan: protobuf format stays exactly the same as in current the current rocksdb branch. We still have a notion of a language bitfield as above, but it moves to the key instead of being encoded into the protobuf, so we now have one rocksdb key per phrase per language, instead of just per phrase, and the language data is encoded as a phrase suffix, similar to how the `.` is used to indicate whether degens are allowed or not in the current implementation.

So, updating the example above might look like:

```YAML
phrase1|lang_mask1: [grid1, grid2, grid3]
phrase1|lang_mask2: [grid4]
phrase2|lang_mask3: [grid5]
phrase2|lang_mask4: [grid6, grid7]
phrase2|lang_mask5: [grid4]
```

In this scenario, current rocksdb's `getbyprefix` stays roughly the same, and `get` becomes more like it. We take advantage of rocksdb's efficient iterating over lexicographically similar entries, so `get` of `phrase1` becomes an iteration of entries with the `phrase1|` prefix (note included separator character -- this is how we get whole words even while doing a prefix scan). We can take advantage of the priority queue work already present in the rocksdb branch to efficiently merge (and penalize, if necessary) the already sorted lists.

With this arrangement, merge can be entirely unchanged vs now, and precached prefixes can be mostly unchanged except that they'll need to preserve the language suffixes.

More thoughts to come on how the penalty will be applied. I think I've come up with a really cheap new way to implement it, assuming we're okay with the limitation that all language-matching features will always beat all non-language-matching features if both exist. I think we can live with that though.

**Comment by apendleton** [comment]
This happened.
