### ISSUE TITLE
country filter not strictly filtering results

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/carmen#588]
### Context
Helpful Info:
* Background
I noticed sometimes the country parameter doesn't seem to be working correctly.

* How to replicate it / where you saw it
https://api.tiles.mapbox.com/geocoding/v5/mapbox.places/570%20bo.json?access_token=ACCESS_TOKEN&country=au

* Expected Result
I didn't expect any results from `jp` when using `country=au`

* Actual result with copied error message
result number 4 and 5 are both from `jp`, `address.10762961557332550` and `address.8407410665969580`

**Comment by mattficke** [comment]
@andrewharvey thanks for flagging this, looks like the param wasn't properly limiting results from one of our indexes. Should be all fixed now.
