### ISSUE TITLE
add street type

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/carmen#597]
It would be nice if carmen had a `street` type, so you could search for a street, and the result would return the full LineString geometry of the street so the map could zoom to the bounds of the street and highlight it on the map.

There is a real world use case behind this.

**Comment by ingalls** [comment]
Carmen itself has no hardcoded types. Outside of address it has no concept of the difference between a street, place, district, postcode etc. All of its logic in terms of how to stack features comes from the config files it is fed on runtime. A full list of these config options can be found in the README with examples of each in the `geocode-unit.*` files in `test/`

Returning a `street` type in a custom carmen instance would simply require setting the config
(ie: https://github.com/mapbox/carmen/blob/master/test/geocode-unit.limit.test.js#L11-L17https://github.com/mapbox/carmen/blob/master/test/geocode-unit.limit.test.js#L11-L17)
as `street` and indexing the streets that you wanted it to be able to return. 

Carmen will then calculate BBOXs for each of the features and if desired return the full linestring.
