### ISSUE TITLE
How to test problematic cases

### ISSUE THREAD

**Issue by yhahn** [mapbox/carmen#62]
One of the ongoing challenges here is problematic cases -- they often involve same/similar terms across multiple indexes and other "noise" inputs.

Only thing I can think to do here is to start capturing these in a separate test suite and see what it's like to build these up over time.

**Comment by ingalls** [comment]
We've started using geocode-unit tests to create both normal geocodes as well as problematic edge cases. https://github.com/mapbox/carmen/blob/master/test/geocode-unit.address-format.test.js
