### ISSUE TITLE
[whitespacequest] Whitespace remover

### ISSUE THREAD

**Issue by yhahn** [mapbox/carmen#631]
Carmen keeps most of its text utility functions in https://github.com/mapbox/carmen/blob/master/lib/util/termops.js.

- [ ] Add  `removeWhiteSpace()` function to this module
- [ ] Add a new unit test file `termops.removeWhiteSpace.test.js`  with tests to confirm the function removes white space greedily (e.g. strings with a single space, multiple spaces in a row, tabs, etc.)

We’ll use this utility function in subsequent steps.

cc @adelrio1

**Comment by adelrio1** [comment]
See PR [#637](https://github.com/mapbox/carmen/pull/637) for details

removeWhiteSpace() passes tests.
