### ISSUE TITLE
[whitespacequest] Collapsed whitespace analysis

### ISSUE THREAD

**Issue by yhahn** [mapbox/carmen#632]
Ping @yhahn to download two simple datasets based on US Tiger — US place names and US address names. These files contain unique text strings separated by line breaks for all US places and US addresses respectively:

    Springersville
    Springerton
    Springerville
    Springfield
    Springfield Acres
    Springfield Census Designated Place
    Springfield Center
    Springfield Corners

etc.

Some example questions we’ll want to answer:

- What percentage of strings in each dataset end up overlapping with others once normalized?
- What are the actual string values that do end up overlapping? Which ones overlap in a potentially positive way (e.g. if  `Lake View Rd` and `Lakeview Rd` collapse, that’s “positive” in that users may expect to find one when searching for the other)? Which ones overlap in a potentially unexpected or negative way?

- [ ] Add a basic no-op CLI command `scripts/whitespace-analysis.js` that can handle an input stream and output the input without any changes
  `cat us-place-text-uniq.txt | ./scripts/whitespace-analysis.js`
- [ ] Modify the script to lowercase and call the whitespace remover utility function on each incoming line
- [ ] Adjust the script to store a mapping between output and input strings and output the results in a format you can use to answer the questions above.

```
# Initial script just normalizes output
Spring Field Town => springfieldtown
Springfield Town  => springfieldtown

# Next pass lets you go backwards from result to possible input values
springfieldtown => ["Spring Field Town", "Springfield Town"]
```

cc @adelrio1

**Comment by adelrio1** [comment]
See PR [#637] (https://github.com/mapbox/carmen/pull/637)

Less than 3% of queries were overlapping. Of those overlapping queries, the differences were minor and easily conceivable as referring to the same place. 

More detailed results are visible in the PR as well.
