### ISSUE TITLE
[whitespacequest] Carmen unit test for whitespacequest

### ISSUE THREAD

**Issue by yhahn** [mapbox/carmen#633]
Carmen unit tests often follow an outline along the lines of https://github.com/mapbox/carmen/blob/master/test/geocode-unit.unicode.test.js.

1. Define a new geocoder (“Carmen”) instance and configuration. Index some data. (https://github.com/mapbox/carmen/blob/master/test/geocode-unit.unicode.test.js#L17-L56)
2. Run some searches against the index and confirm that the searches find the expected results. (https://github.com/mapbox/carmen/blob/master/test/geocode-unit.unicode.test.js#L58-L132)
3. Clean up. (https://github.com/mapbox/carmen/blob/master/test/geocode-unit.unicode.test.js#L135-L138)

Each of these tests usually differ in that they target specific functionality based on what they index and what they expect to find based on that data. For example, the test above focuses on how carmen handles unicode characters. Other tests focus on how results are ranked and prioritized, how addresses are returned, and so on.

- [ ] Add a new unit test `test/geocode-unit.whitespace.test.js`
- [ ] Index a feature with a string that includes whitespace
- [ ] Query the index for that string including whitespace and excluding whitespace and assert that it finds the feature in both cases

cc @adelrio1

**Comment by aaaandrea** [comment]
This was merged in [#637](https://github.com/mapbox/carmen/pull/637)
