### ISSUE TITLE
[whitespacequest] Apply whitespace normalization to indexing & query runtime

### ISSUE THREAD

**Issue by yhahn** [mapbox/carmen#634]
The carmen search and indexing code are both pretty gnarly but for this work we’ll touch only where text gets processed and normalized. 

- [x] Index time: Ping @yhahn or another geocoding team member for a walkthrough of `indexdocs.js`
  - Processed text before it gets stored in the index
  - https://github.com/mapbox/carmen/blob/master/lib/indexer/indexdocs.js#L278
- [x] Query time: Ping @yhahn or another geocoding team member for a walkthrough of `phrasematch.js`
  - Text from a search query that will be looked up in each index's autocomplete text data
  - https://github.com/mapbox/carmen/blob/master/lib/phrasematch.js#L37
  - Text from a search query that will be looked up in each index's spatial data
  - https://github.com/mapbox/carmen/blob/master/lib/phrasematch.js#L110
- [x] Introduce whitespace normalization at these two phases and use the whitespace unit test to debug and iterate
- [ ] Once the above test is working, run through the remaining tests and see what other changes might be necessary to get the whole system to accommodate this change

cc @adelrio1

**Comment by yhahn** [comment]
@adelrio1 per voice, let's robustify testing the whitespace functionality by testing for a street within a city as well, e.g. a query like `wall st new york`

- [ ] Adjust your carmen config to include both a city and street index rather than just a `test` index -- you can use the stacky test as a guide for setting up multiple indexes (https://github.com/mapbox/carmen/blob/master/test/geocode-unit.stacky.test.js#L13-L18)
- [ ] Index Wall St as part of the `street` index
- [ ] Index New York as part of the `city` index, but switch its type to a `Polygon` rather than a `Point` so that the wall street feature is encompassed within it. You can use http://geojson.io to map both features you want to index
- [ ] Add a test that queries for `wall st new york` and confirms it finds the wall st feature
- [ ] Add a test that queries for a variation in a whitespaceless way that you think should work, like `wall st newyork`

**Comment by aaaandrea** [comment]
This was merged in [#637](https://github.com/mapbox/carmen/pull/637)
