### ISSUE TITLE
[whitespacequest] Overview

### ISSUE THREAD

**Issue by yhahn** [mapbox/carmen#635]
:wave: @adelrio1 - this ticket will help you track the big picture of your sprint project.

### Background

We'll be looking at one possible way of implementing an aspect of "fuzzy search" in this project - being more tolerant of variations in white space in queries. For example, users currently may search for "Lake View Road" and will not get any results if the only address features in our data have been indexed as "Lakeview Road". We'll be looking at an approach to solving this problem which collapses whitespace when indexing and querying in specific chunks of text.

### Goal

The goal of our work is to:

1. Assess the viability of collapsing whitespace behind the scenes when matching text — will this introduce unexpected search results to users?
2. Implement and unit test the basic mechanics of removing white space from indexed text as well as queries in carmen.

### High-level backlog overview

- Write a utility function that greedily removes whitespace from carmen subqueries and add unit tests for the functionality (https://github.com/mapbox/carmen/issues/631)
- Create a cli tool to read input text from a stream and gather stats on strings that will have identical representations when indexed without whitespace (https://github.com/mapbox/carmen/issues/632)
- Write a carmen test that expects the same results for a query with and without whitespace (https://github.com/mapbox/carmen/issues/633)
- Walk through the indexing and query tokenization process and identify key spots to apply whitespace removal. Confirm initial test passes and that other tests are unaffected by functionality (and if they are… debug!) (https://github.com/mapbox/carmen/issues/634)

We use pull requests to contribute work and close issues - a 1:1 relationship between each PR and issue. To break this work up into small stages for the sprint, we’ll stand up an empty PR and then PR each major change against that, until the original PR is ready to merge into master. Ping @yhahn if this is confusing, or if you need pointers on submitting a pull request!

cc @adelrio1

**Comment by aaaandrea** [comment]
This was merged in [#637](https://github.com/mapbox/carmen/pull/637)
