### ISSUE TITLE
Feedback on Germany's geocoding results

### ISSUE THREAD

**Issue by carocad** [mapbox/carmen#639]
### Context

I am currently using the geocoding api v5 which is what I think this repo is about but I couldnt find any reference to it on the Docs.

I am currently looking for addresses in Frankfurt, Offenburg and Freiburg in Germany. Nevertheless the geocoding results are quite poor. This has been quite a surprise since if I manually look the place up in the map, I can find it but the geocoder cannot :/

Use the geocoder to find places that are clearly visible in the map. For example:
- Frankfurt West (train station @ 50.119161, 8.639571)
- Europaische Zentralbank (bank @ 50.108794, 8.703343)

The geocoder should correctly find out the places that are input if they are actually present in the map.

### Next Steps

I have checked both photon and google maps to see if there was a common pathology, but I couldnt find it.

Afaik you are using OSM and propietary data to provide the geocoding service. In my case I dont want to have to bother myself with setting up a service of my own nor on switching to another map provider with propietary info (google, here, etc). So I propose the following approach to identify the underlying problem.

whenever a user would search a place:
- if mapbox geocoder returns a results that the user selects --> do nothing
- if mapbox geocoder returns an empty array (no results) --> request `photon.koomot.de` geocode
- if `photon.geocoder` returns a result that a users selects -->
  - store the search criteria and the results from both mapbox and photon

Every once in a month or so I would publish that information (json) on an github issue. Since photon uses OSM data (public) I guess it shouldnt be a problem to compare and store its search results.

Let me know your thoughts

**Comment by ingalls** [comment]
Hey @carocad, appreciate you taking the time to write to us. At the moment we do not use OSM in the geocoder for Germany results, instead relying on a wide variety of 3rd party data providers for results.

From our tests our address coverage should be rooftop level for most of the country, the two examples that you gave come from our `POI` layer. At the moment we haven't deployed complete data from our German POI data provider, instead rolling our select categories at a time to ensure consistent and high quality results (It's a ton of data!)

For future problems with queries in our geocoder I would invite you to report them here: https://www.mapbox.com/geocoder-feedback/. They can then be reviewed by one of our engineers on the geocoding team. This repo is for the underlying geocoding engine itself which is data agnostic and not tied to the results shown through the mapbox API. (Though it does power the mapbox API)

In regards to your second query, You are more than welcome to use the mapbox geocoder in conjunction with another geocoding provider to back-fill the results where you see fit. The proposed outline looks like a solid plan and should be do-able from the user side of your application.

The only thing I would caution you against is that as per our TOS the `mapbox.places` geocoding endpoint does not allow results to be stored or saved in any way and results must be displayed on a map. To store geocdoes permanently you would need to contact our sales team about the `mapbox.places-permanent` endpoint.

All the best,
Nick
