### ISSUE TITLE
documentation: first steps

### ISSUE THREAD

**Issue by luca-dall** [mapbox/carmen#669]
Hallo!

I'm trying to use carmen with my datasets but I'm not seeing a simple documentation...

I have Land/states/towns and postal codes polygons as well as addresses points.

I suppose I need to store the mbtiles in a folder and then?
Is there a pipeline to prepare (analyze, index, ...) the data?
Is there a backend that should run to send a request?

Thank you in advance!

**Comment by ingalls** [comment]
Hey @luca-dall 

You'll need a couple of things to be able to generate indexes that are compatible with carmen. 

The first is an mbtiles vector file that contains the data you want in the index. Make sure that your input data has the required properties. The list of properties can be found here: https://github.com/mapbox/carmen#getindexabledocspointer-callback Any properties not prefixed with `carmen:` will be output with the feature.

To generate this initial MBTiles file I would recommend using something like mapobx/tippecanoe

Once you have your vector MBTiles file you can generate indexes using:
https://github.com/mapbox/carmen/blob/master/scripts/carmen-index.js

Which will append them onto the existing mbtiles file as well as creating a corresponding `.rocksdb` file.

It should be noted that each layer should be a separate layer - ie mbtiles file. So you will want to repeat th above process once for address, place, postcode, etc.

Unfortunately although we open source the carmen and associated tools, we don't open source our internal server infrastructure. That said it's not too difficult to set up your own and each of the unit tests in the `test` directory do just this!

**Comment by luca-dall** [comment]
Thanks for your help!
I will try to create the mbtiles with the carmen: proprieties and use them.
At the moment I'm only planning to do some local testing :)

**Comment by ingalls** [comment]
Feel free to open another ticket if you run into any problems
