### ISSUE TITLE
[routablequest] 1. Setup

### ISSUE THREAD

**Issue by yhahn** [mapbox/carmen#673]
For your sprint project, we'll add a `routable_point` property to address geocoding results in carmen where the data can support it.

**Set up git:**

- [x] Git credentials configured locally on loaner laptop - your [username](https://help.github.com/articles/setting-your-username-in-git/) and [email](https://help.github.com/articles/setting-your-email-in-git/).
- [x] [SSH for GitHub](https://help.github.com/articles/connecting-to-github-with-ssh/) configured.

**Set up basic file structure:**

- [x] Clone this repo
- [x] Run `npm install` and `npm test` to make sure your setup works
- [x] Check out a new clean `routablequest` branch locally

    ```
    git checkout -b routablequest
    ```

- [x] Push your branch to Github

    ```
    git push origin routablequest
    ```

This branch will be the target for your sprint PRs - before other steps, you'll create new branches off of this one (e.g. `routablequest-docs`) and PR against this one.

Once you're done with those steps, close this issue.

cc @nmargolis @mattficke @apendleton

**Comment by Nmargolis** [comment]
Done!
