### ISSUE TITLE
De-indexing, index-updating

### ISSUE THREAD

**Issue by yhahn** [mapbox/carmen#69]
Once https://github.com/mapbox/carmen/issues/67 is complete we should have an index structure that allows for deletes and updates.

- **Design API**. Currently all docs passed into `index()` are considered creates. Should there be different methods, or should each index have an operation/action associated with it?
- Need a process for index updates that does not take results offline -- e.g. if we're going to delete index records before updating them ideally it is done in one pass.

**Comment by ingalls** [comment]
Going to close this as we don't currently have any plans to allow de-indexing as it is basically impossible with the DAWG index.

**Comment by apendleton** [comment]
@ingalls I think some of the merge work actually lays the foundations for this on the DAWG side. We'd have to rebuild the DAWG index without the missing item, but I think it could be done pretty efficiently (on the order of minutes for the biggest indexes).
