### ISSUE TITLE
most tests for merge are missing overlapping shard values

### ISSUE THREAD

**Issue by boblannon** [mapbox/carmen#692]
### Context

With the exception of `index.merge.bench.test.js`, most of the merge tests involve fixtures that don't share any shard values. When creating `indexA` and `indexB`, the tests grab non-overlapping slices of `test/fixtures/docs.jsonl`.  This means that the branch of the merge logic that actually applies the `mergeOp` function is never reached, because there are no cases where `data1` and `data2` are both defined:

https://github.com/mapbox/carmen/blob/3350d631dae7c947a726bcb1e2ea8489c22c0be3/lib/merge.js#L96-L105

### Next Steps

- create two separate fixtures (with some overlapping shard values) to test merge behavior more "honestly"
- adjust expected values as needed

**Comment by apendleton** [comment]
Merge is dead. Stale.
