### ISSUE TITLE
Mapbox geocoder POIs inconsistent with map view

### ISSUE THREAD

**Issue by nbolten** [mapbox/carmen#696]
### Context

The 'Mapbox Streets' style shows a large number of POIs that are not found when geocoding for those exact names, with or without the 'proximity' setting. Please let me know if there is a better repo for reporting and tracking this issue, since it's not really Carmen's fault.

While this type of issue has been reported before (#639), it is impossible to track any progress on it. In addition, the recommended solution was to use the 'single bad geocoding result' feedback page for Mapbox, while this is a more systematic issue.

It seems clear that this is a data issue: the data used to generate some of the POI layers on 'Mapbox Streets' is not used in the geocoder. This leads to a confusing and frustrating user experience: users can see important POIs on the map, but can't route to them using a search.

### Examples

Most visible POIs on a zoomed-in downtown Seattle map aren't found when using the mapbox geocoder. This includes major destinations and/or civic spaces for both locals and tourists:

* Seattle Central Library: {"lng":-122.33272372061688,"lat":47.60677994456799}
* Seattle City Hall: {"lng":-122.32989943399517,"lat":47.6038663151568
* Washington State Convention Center: {"lng":-122.3315900580242,"lat":47.61176471461013}
* MoPOP: Museum of Pop Culture: {"lng":-122.3482550064254,"lat":47.62146626431692}
* Virginia Mason Medical Center: {"lng":-122.32785594113044,"lat":47.610194822110714}
* Harborview Medical Center: {"lng":-122.32403097948364,"lat":47.604329977324426}

#### Expected Result
The mapbox geocoder finds visible and marked POIs.

#### Actual result
Most marked POIs can't be geocoded.

### Next Steps

One option is to identify the exact POI layer that isn't included in geocoder results, if the issue is confined to a single layer.

However, because these POIs are so important (the convention center alone has thousands of out of town visitors a day), this seems like import missing functionality, so it would be great to track any progress on this issue.

**Comment by mattficke** [comment]
@nbolten Thank you for the feedback, we're always working to improve the data in our products. You're correct that the data used in the Mapbox Geocoding API is not the same as that in the Mapbox Streets visual basemap. This repo is for the Geocoding engine itself, and isn't the best place to track product or data issues. For your particular situation I'd recommend reaching out to cities@mapbox.com, they'll point you in the right direction.

**Comment by nbolten** [comment]
Does Mapbox have a public issues section for something like this? Downstream open source projects could use an issue for referencing + coordination.
