### ISSUE TITLE
Node.js 8.x

### ISSUE THREAD

**Issue by TanZhangzhi** [mapbox/carmen#707]
### Context

I'm using Node.js 8.11.1 LTS and could not run this project on Ubuntu. I tried to uninstall Node.js 8.x and install 6.x but fail. I wonder if this project can run under Node.js 8.x or got any plan to update to Node.js 8.x.

**Comment by ingalls** [comment]
@TanZhangzhi can you provide

- The name and exact version of the package manager you are using (npm, yarn, etc)
- Your OS & version

I've run the project under Node 10 and haven't had any trouble but we currently only officially support 6.

**Comment by ingalls** [comment]
If this is still a problem feel free to reopen a ticket providing the above information.
