### ISSUE TITLE
Circle CI lint testing broken

### ISSUE THREAD

**Issue by samely** [mapbox/carmen#736]
### Context
As per [`comment`](https://github.com/mapbox/carmen/pull/735#pullrequestreview-146130226) about linting test fails broken. We need to fix the configuration so the test fails if any lint error.

### Next Steps
- [ ] Fix config for testing lint

@apendleton

**Comment by apendleton** [comment]
@samely did you want to do this one too or should I take it?

**Comment by samely** [comment]
Either way @apendleton I was just ticketing. If you can do it would be great. Thank you ^^
