### ISSUE TITLE
Limit compounded effect of token replacement + fuzzy matching

### ISSUE THREAD

**Issue by boblannon** [mapbox/carmen#757]
### Context
We should be careful about the interaction between token replacement and fuzzy matching. It's possible we should disallow fuzzy-matches on any token that has undergone token replacement.

The example case for this is `30th station phila, pa`. It is currently passing in production, where it returns 30th Street Station in Philadelphia.  When `SPATIALMATCH_STACK_LIMIT` is increased even to 40, 30th Street (the street in Philadelphia) matches, so it's lurking as a match just below the cutoff. 

Looking at debug output, it's clear that the street is matching this query because `"station"` has been abbreviated to `"stn"` and it fuzzy-matches `"st"`, the abbreviation for `"street"`.  I think this is a separate issue that we need to look into: the interaction between abbreviation token replacement and fuzzy-matching occasionally causes the wrong features to get bumped down.  In this case:

```
Tokens
------
30th, station, phila, pa

Features
--------
- 0.98 North 30th Street, Phila, Pennsylvania 19104, United States (address.81234238635188
68)
- 0.98 South 30th Street, Phila, Pennsylvania 19104, United States (address.87221036165018
46)
- 0.98 S 30th St, Phila, Pennsylvania 19104, United States (address.6672153668866792)
- 0.98 North 30th Street, Phila, Pennsylvania 19121, United States (address.71831808324232
40)
- 0.98 South 30th Street, Phila, Pennsylvania 19146, United States (address.81532256379386
52)

Indexes
--------
- mapbox.places-us_northeast-address-both
- mapbox.places-us-neighborhood-both
- mapbox.places-us-postcode-both
- mapbox.places-namopen-place-both
- mapbox.places-aa-region-both
- mapbox.places-aa-country-both
- mapbox.places-nam-poi-ephemeral

Debug
=====
id: 330952
extid: 2428104

PhraseMatch
-----------
   mapbox.places-us_northeast-address-both {"pa":0.25,"phila":0.25,"peila":0.25,"phil":0.25,"philo":0.25,
      "philp":0.25,"phils":0.25,"shila":0.25,"stn":0.25,"30th":0.25,"phila pi":0.5,
      "phila pk":0.5,"30th mtn":0.5,"30th st":0.5}
   mapbox.places-nam-poi-ephemeral {"30th st":0.5,"phila pa":0.5,"phil pa":0.5,"30th stn": 0.5,"philp pa":0.5,
     "phils pa":0.5,"philo":0.25,"philau":0.25,"30th":0.25,"phia":0.25,"phils":0.25,
     "stn":0.25,"philz":0.25,"phina":0.25,"shila":0.25,"pa":0.25}                      

[...] 

SpatialMatch
------------
spatialmatch position: 8
{
  "relev": 0.9333333333333333,

[...]

VerifyMatch
-----------
verifymatch position: 6
```

**Comment by apendleton** [comment]
Yup, this is definitely a known issue. It came up in the "Rhode Island Ave" testing as well, where "Island" => "Is" matched like a gazillion things.

> It's possible we should disallow fuzzy-matches on any token that has undergone token replacement

Fuzzy-phrase doesn't currently expose a way to specify different replacement behavior for individual tokens within a phrase, so we have no easy way of doing that. Anyhow, what I've wanted to do since forever is to move token replacement itself into fuzzy-phrase, so that fuzzy-phrase is aware of both the expanded and contracted variants of each word, and spelling correction happens before replacement. But obviously we'd need to build that out.

**Comment by boblannon** [comment]
> what I've wanted to do since forever is to move token replacement itself into fuzzy-phrase, so that fuzzy-phrase is aware of both the expanded and contracted variants of each word, and spelling correction happens before replacement. 

ah yeah, i forgot we were looking at that.  maybe a short-term fix would be to increase the threshold for fuzzy matching tokens. we're currently at 1, but upping that to 3 would address about 50% of the tokens that are produced by token replacement.

**Comment by apendleton** [comment]
Done in #803
