### ISSUE TITLE
Revisit result sorting to sort on a single composite incorporating relevance and score/proximity

### ISSUE THREAD

**Issue by apendleton** [mapbox/carmen#771]
### Context
Currently, carmen sorts first on relevance and then, as a tie-breaker, on proximity and score. For results with large relevance differences, this is good: results that match most or all of the user's query clearly better match the user's intent than ones that only match parts of it (e.g., a complete match for a fully qualified address rather than a partial match for only the city or only the housenumber and street), even if those partial matches are nearby. However, for two matches that are of very similar but not identical relevance, often due to a small penalty applied for an out-of-language match or a fuzzy match (i.e., a typo), we often end up matching very far-away things that share that typo or happen to be in that language when the user wanted something that was almost as good a much but was closer (or more salient).

We should experiment with a new approach where, rather than sorting first on relevance and then on proximity/score, we construct a single composite value that's dominated by relevance but allows small relevance differences to be overtaken by large proximity or score differences. To start, we could consider a weighted average of, say, 90% relevance + 10% prox/score, and see what happens.

We'll probably want to test on three classes of queries where we know this is a problem:
* language penalties
* typos
* word frequency penalties (e.g., matching variants that have been auto-indexed at reduced relevance without "the")

each of these might have a slightly different magnitude of penalty, and also gets its penalty applied in a different place, so we may not have equal success with all of them.

### Next Steps
- [ ] first let's try just doing this in verifymatch: https://github.com/mapbox/carmen/blob/master/lib/geocoder/verifymatch.js#L398
- [ ] we may also have some features that don't even make it to verifymatch because they get lost in a similar sort in carmen-cache, so we may need to address it there as well

**Comment by lizziegooding** [comment]
Done in https://github.com/mapbox/carmen/pull/777
