### ISSUE TITLE
Revisit how we deduplicate features

### ISSUE THREAD

**Issue by lizziegooding** [mapbox/carmen#823]
particularly addresses

### Context
While writing tests for https://github.com/mapbox/carmen/pull/822, I looked at how we current remove duplicate features before we return them to the user https://github.com/mapbox/carmen/blob/master/lib/geocoder/dedupe.js. We remove duplicate features if they have the exact same `place_name` and only return whichever feature happens to be sorted first. If one of those exact matches has its `geometry.omitted` property set to `true`, we drop that feature instead.

One example of problems with this deduping functionality is how we handle addresses with slightly different names. For example, a query for `1013 N Bonnie Brae St` in Los Angeles returns both an interpolated and a non-interpolated result, but because their place names don't exactly match (one is `1013 N Bonnie Brae St` and the other is `1013 North Bonnie Brae Street`), we return both.

![image](https://user-images.githubusercontent.com/18095166/52503642-28323f00-2bb4-11e9-92d2-3b89dff75b00.png)

### Next Steps
We should consider doing a smarter deduplication at query time that takes into account:
- if token-replaced `place_name`s are the same
- how proximate the features are; this is unlikely but it's probably possible to have two features with the exact same `place_name` in totally different parts of the world

cc @mapbox/search

**Comment by miccolis** [comment]
With #846 we're put de-duplication in place that should address the issues in the OP, the query for "1013 N Bonnie Brae St Los Angeles California 90026" now returns;

![Selection_080](https://user-images.githubusercontent.com/77205/55183662-b2cffd00-5166-11e9-915d-712ef5448e08.png)

The approach take here looks at the text that was used to find the match and the elements of a result that are assembled into it's display name. This avoids attempting to redo or undo token replacement and leverages the display format to indicate what elements of a context should be used to determine uniqueness.

Closing, but @lizziegooding if I'm missing anything please reopen.
