### ISSUE TITLE
Don't use category synonyms for matching text.

### ISSUE THREAD

**Issue by apendleton** [mapbox/carmen#828]
### Context
We currently supply `matching_text` and `matching_place_name` fields on some responses, if the thing the user typed is more similar to a synonym or translation on a feature other than the one that's the default label in the user's requested language (for example, if the user types "Deutschl" with language=en, `text` might be `Germany` while `matching_text` might be `Deutschland`). If category information for points of interest is included on features as synonyms, though, this leads to weird behavior where, for example, the `matching_text` field for all results in a search for `coffee` is just `coffee`, and the `matching_place_name` field might be `coffee, washington, dc`. This is not likely to be useful to end users, so we should skip emitting matching_text/matching_place_name data in this circumstance.

Matching text is determined in the `getMatchingText` function here: https://github.com/mapbox/carmen/blob/master/lib/geocoder/ops.js#L226 and as of #758 we now have a list of all the categories in an index attached as metadata to the index's configuration. We also have a reference to the `geocoder` object from within the `getMatchingText` function. We should have all the pieces necessary to just skip attaching matching text in the event that thing we were going to attach is in the category list, fi present.

cc @lizziegooding 

### Next Steps
- [x] add new matching text functionality
- [x] tests

@mapbox/search

**Comment by Nmargolis** [comment]
Done in #855
