### ISSUE TITLE
Postal Overrides

### ISSUE THREAD

**Issue by ingalls** [mapbox/carmen#839]
### Context

Now that support for the `carmen:addressprops` feature has launched, we should explore the ability to allow lower features to override parts of the `context` array in the resultant feature.

Since postal polygons will always have a certain degree of error due to their conversion from routes, this will provide a method in which we can error correct using known postal information about a given address.

#### Overriding
There are two potential parts to this quest - the first is simply overriding the `context` at the end of verifymatch. It could potentially look like something like:

**Address Feature Props**
```
override:postcode: 26884
override:country: 'United States'
```

Where features with these properties would get first dibs at filling in the `geocoder_format` value, before being removed from the properties object.

Gotchas: The context has a feature id that would need to be overwritten as well.

#### Indexing

The second potential operation is to include the postcode in the indexes to allow forward searches for addresses with postal codes that do not match their corresponding postal polygon. I am less confident of the feasibility of this approach.

@mapbox/search

**Comment by miccolis** [comment]
This is available in Carmen 28.5.0
