### ISSUE TITLE
Prefering matches in a single index can hide desired result

### ISSUE THREAD

**Issue by miccolis** [mapbox/carmen#849]
This materializes when we have a match in a single index, like a POI which is less desireable than a match for a very highly scored feature, but the query happens to have span two indexes. In both the below examples the user expects a city with the name of their query;

* "San Francisco CA" => "San Francisco Cable Car"
* "Hartfort CT" => "Hartford Court"
* "Portland OR" => "Portland Oregon Temple"

The sort that prefers these single index matches is https://github.com/mapbox/carmen/blob/master/lib/geocoder/spatialmatch.js#L41

...and it's going to be tricky to work around it, we've got limited information at this stage. Raising the `spatialmatch_stack_limit` may help, or somehow prefering exact (non-autocomplete) matches.

**Comment by ingalls** [comment]
Ref: https://github.com/mapbox/geocoder-feedback/issues/2773

**Comment by Nmargolis** [comment]
This was addressed in #906
