### ISSUE TITLE
Ampersand replacement to 'and' for intersections.

### ISSUE THREAD

**Issue by miccolis** [mapbox/carmen#858]
I'm attempting to replace ampersand with 'and' to use that separator for intersection search. It's not working. The replacement I'm using is;

```
"(.+) & (.+)": { "regex": true, "spanBoundaries": 1, "text": "$1 and $2" }
```

So the query comes in for `1st & main st`

```
{
    tokens: ["1st", "main", "st"],
    separators: [" & ", " ", ""],
    owner: [0, 1, 2]
}
```

We token replace the `&` and normalize that into

```
{
    tokens: ["1st", "and", "main", "st"],
    separators: [" ", " ", " ", ""],
    owner: [0, 0, 0, 2]
}
```

In phrasematch the results we generate are a little weird because of the cardinality changing replacement. We do "Gap expansion" and end up with 2 matches that differ just in the mask. Presently we generate;

```
    mask: 1, phrase: "+intersection 1st , main st",
    mask: 3, phrase: "+intersection 1st , main st"
```

This seems wrong. I'd expect the expanded mask to be `111` not `011`. Then when we calculate a weight for the match it ends up being `0.666..` and not `1`. So then we've got a bad mask that could potentially allow incorrect matches AND a weight that would sinks the single index match we're looking for.

**Comment by samely** [comment]
Question @miccolis
Do we prefer street names results over intersection results? In cases where the street name contains `&` char in its name.

**Comment by miccolis** [comment]
@samely I suspect the indexing process would remove `&` from street names. As we're not actually replacing ampersand yet now is the right time to figure out these sorts of implications. Do you have an example or two of a street name that has an ampersand?

**Comment by samely** [comment]
Yeah...

```
40 M&W Lane, Waynesboro, Virginia 22980, United States
130 Smith & Brogdon Rd, Chase City, Virginia 23924, United States
11720 Lewis & Clark Dr, Lolo, Montana 59847, United States
2590 Coach Surrey Ln Part, Aurora, Illinois 60506, United States
```

**Comment by miccolis** [comment]
At this point #859 fixes the issue here and thankfully it's a small change that is limited to intersection code. Further details on the issue are there.

@samely to give your question a more complete answer; the replacement I'm proposing that we add would normalize ` & ` to ` and `. This would work both for street names and intersections queries that match the pattern `[space]&[space]`.

So where right now we index `Smith & Brodgon` as `smith brogdon`, with this change we'd index it as `smith and brodgon`. This should work find as we'd normalize user input the same way, and in fact it should also allow searches for `smith and brodgon` to surface the street without any penalty.

This change, as currently planned, would not do anything differently to `M&W`.  It does seem like we could normalize "&" to "and" in cases like this, but I think that needs further study and I don't think we want to expand the scope here.

**Comment by samely** [comment]
Thanks for your clear notes! Definitely a better response without penalty.

**Comment by aarthykc** [comment]
Done in https://github.com/mapbox/carmen/pull/859
