### ISSUE TITLE
Geocoding can't find streets on map

### ISSUE THREAD

**Issue by andreolikalcopoli** [mapbox/carmen#923]
### Context
I am developing app with MapBox maps. I am searching for Serbian streets, but I can't get coordinates for any of them. I used everything to specify in which region it should be searched, but nothing helps.
I saw the problem when I wanted to find some street from my country. There are no results for most of the streets.
I want to have coordinates for each street and each address, so I can navigate the user to that point.
Every time, geocoding returns zero results.

### Next Steps
I've searched around MapBox documentation, specified region where the app should search, tried with multiple languages, but nothing helps.

@mapbox/search

**Comment by ingalls** [comment]
Hey @andreolikalcopoli This repo is for the core geocoder itself, it does not handle data that Mapbox has loaded into it via their API.

It sounds like you have already done this - but you can use the [Search Playground](https://docs.mapbox.com/search-playground) to build API requests with the various parameters that the API supports. Based on the playground it does not look like there is currently street data loaded for serbia.

[https://www.mapbox.com/contact/](Mapbox Support) is awesome, and they can tell you for sure if this is the case.

**Comment by andreolikalcopoli** [comment]
Hello @ingalls 
Thank you for your time. I've already contacted Mapbox Support. I thought that the problem was from my side, or I have to do something, but now I can see that the problem is not having street support for Serbia. 
Thank you, have a nice day!
